### ISSUE TITLE
Cannot sign in to Company Communicator app

### ISSUE THREAD

**Issue by Larryngolog** [OfficeDev/msteams-sample-line-of-business-apps-csharp#56]
After I sideload the company communicator app I get redirected to the personal conversations to configure the app. Unfortunately nothing happens when I click on the "Sign in" button.

**Comment by Wajeed-msft** [comment]
I'll look into this issue. Could you please share your Tenant's current setting for [external apps](https://docs.microsoft.com/en-us/MicrosoftTeams/enable-features-office-365#external-apps)?

**Comment by Larryngolog** [comment]
![image](https://user-images.githubusercontent.com/18740551/55824734-c5521b00-5b04-11e9-8f95-98e29ebfa947.png)

**Comment by Wajeed-msft** [comment]
@Larryngolog, @PeppeDotNet - Could you please try it one more time? You might need to send help command one more time.

**Comment by Larryngolog** [comment]
Hi! Today I tried with another account and it worked as expected.
