### ISSUE TITLE
Documentation for group excel file

### ISSUE THREAD

**Issue by Larryngolog** [OfficeDev/msteams-sample-line-of-business-apps-csharp#60]
Hi! To define groups in communicator we should upload the excel file with definition of groups.
Is there any documentation what this excel file should and can contain and what will be the result?
For example:

- Is it possible to input not only users but also Office 365 and Azure AD groups?
- Is it possible to include everyone?
- Is it possible to define dynamic groups - like everyone with department equal to HR?
- is it possible to nest communication groups to have a tree like structure that reflects org structure?

Thanks!

**Comment by Wajeed-msft** [comment]
We have updated UI to put in more information. 
![image](https://user-images.githubusercontent.com/31851992/61100235-01d63f80-a483-11e9-8c52-cdfb5cfd3231.png)

- Is it possible to input not only users but also Office 365 and Azure AD groups? **Yes**
- Is it possible to include everyone? **Yes**
- Is it possible to define dynamic groups - like everyone with department equal to HR? **No, but you can modify code to do that.**
- is it possible to nest communication groups to have a tree like structure that reflects org structure? **No, currently it is flat structure. But you can be modify the code to do that.**
