### ISSUE TITLE
Cross Vertical - Low Code No Code Approvals - Get Item (Id)

### ISSUE THREAD

**Issue by isawek** [OfficeDev/msteams-sample-line-of-business-apps-csharp#64]
Hi, and thanks for the "Low Code No Code Approvals".

In Flow I can´t add the dynamic content "Id". i think the request json should contain an id of type number instead of string. or do i have to use the expression triggerBody()?['id']

**Comment by Wajeed-msft** [comment]
It doesn't show the dynamic input when you are editing JSON body. As workaround you can add dynamic values in headers first and then cut paste in body.

**Comment by isawek** [comment]
but after changing the type to numer ther is a dynamic content under "When a HTTP request is received". after changing it back to string it dissapears.
