### ISSUE TITLE
Cross Vertical - Low Code No Code Approvals - Item Created Post Json

### ISSUE THREAD

**Issue by isawek** [OfficeDev/msteams-sample-line-of-business-apps-csharp#65]
When creating an http action after the item created action, i get an error while saving the flow with te json. 

The template validation failed: 'The template action 'HTTP' at line '1' and column '1672' is not valid: "Unable to parse template language expression 'type': expected token 'LeftParenthesis' and actual 'EndOfData'.".'.

i used your json template and just changed the target path to my HTTP Post URL

**Comment by Wajeed-msft** [comment]
Put double @ for JSON keys like "@@type".

**Comment by isawek** [comment]
thank you for your fast answer. i used this template: https://github.com/OfficeDev/msteams-sample-line-of-business-apps-csharp/blob/master/Cross%20Vertical/Low%20Code%20No%20Code%20Approvals/Connector%20Card%20JSON%20payload.json

and there already are double @ for Keys

**Comment by isawek** [comment]
or do i have to add them before "@{triggerBody() too?

**Comment by isawek** [comment]
ok i fount it there is a missng @ at "@type": "ActionCard",
