### ISSUE TITLE
Cross Vertical - Low Code No Code Approvals - Parse JSON 2 error

### ISSUE THREAD

**Issue by isawek** [OfficeDev/msteams-sample-line-of-business-apps-csharp#66]
hi again :)

in the second flow at approval / rejection i get the following error:

![Error](https://user-images.githubusercontent.com/31202872/63523073-c1de8f80-c4f9-11e9-93ed-163bf7d6496b.png)

**Comment by Wajeed-msft** [comment]
Could you please try this and let me know if it works for you?

`base64ToString( concat(split(body('Parse_JSON')?['Action-Authorization'],'.')[1], '='))`

**Comment by isawek** [comment]
No it doesn´t work.

InvalidTemplate. Unable to process template language expressions in action 'Parse_JSON_2' inputs at line '1' and column '1878': 'The template language function 'base64ToString' was invoked with a parameter that is not valid. The value cannot be decoded from base64 representation.'.

**Comment by Wajeed-msft** [comment]
Could you please try few solutions posted in comments sections below? 

https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Building-low-code-no-code-approval-workflows-for-your-team-using/bc-p/707485/highlight/true#M3356

Also, can concatnate  **==** once and check.

**Comment by isawek** [comment]
base64ToString(split(body('Parse_JSON')?['Action-Authorization'], '.')[1])

worked for me :)
